services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: ppass
      POSTGRES_DB: store_default
    ports:
      - "5432:5432"
    volumes:
      - dbops_postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dbops_postgres:
