name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Установка JRE
    - name: Install Java Runtime Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jre

    # Установка Flyway
    - name: Install Flyway
      run: |
        wget -qO flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz
        tar -xzf flyway.tar.gz
        sudo mv flyway-10.7.1 /usr/local/share/flyway
        sudo ln -s /usr/local/share/flyway/flyway /usr/local/bin/flyway
        flyway -v

    # Запуск миграций с Flyway
    - name: Run Flyway migration
      env:
        DB_USERNAME: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_URL: jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
      run: |
        flyway -user=$DB_USERNAME -password=$DB_PASSWORD -url=$DB_URL info
        flyway -user=$DB_USERNAME -password=$DB_PASSWORD -url=$DB_URL migrate

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
